### ISSUE TITLE
Whats that

### ISSUE THREAD

**Issue by ZehJulianLp** [TornRPG/bugs#2]
![image](https://user-images.githubusercontent.com/79467458/162296717-624fe9b3-7d2c-4778-b9c3-0328891c8d36.png)

Da fehlt was in der Mitte

Es kam einfach so xD

**Comment by ZehJulianLp** [comment]
new webhook

**Comment by StonkDragon** [comment]
![Bildschirmfoto 2022-04-08 um 18 46 46](https://user-images.githubusercontent.com/76126874/162486194-cc87cadf-ef26-4699-97fb-2ee016d352be.png)

Fixed
